### ISSUE TITLE
支付宝小程序选择项高量问题

### ISSUE THREAD

**Issue by AaronLucas** [SongLazy/sl-filter#1]
demo演示中，并列菜单，弹出后，无法高亮显示选中的东西，其实已经选中了，view没刷新。能帮着看看怎么解决么，谢谢。

**Comment by AaronLucas** [comment]
独立菜单就根本没法显示，其实应该也选中了，点确定看输出是有变化的。

**Comment by SongLazy** [comment]
你在filter-view.vue中的itemTap方法的最后，加一行this.$forceUpdate();，  或者把ifdef H5的判断去掉




------------------ 原始邮件 ------------------
发件人: "AaronLucas"<notifications@github.com>;
发送时间: 2019年7月5日(星期五) 下午5:40
收件人: "SongLazy/sl-filter"<sl-filter@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [SongLazy/sl-filter] 支付宝小程序选择项高量问题 (#1)




demo演示中，并列菜单，弹出后，无法高亮显示选中的东西，其实已经选中了，view没刷新。能帮着看看怎么解决么，谢谢。

**Comment by AaronLucas** [comment]
Ok,找到了，谢谢，我是写能了 #ifdef H5 MP-ALIPAY

**Comment by SongLazy** [comment]
ok,nice.
